#!/bin/sh

. ${srcdir}/testing.sh

tst_start

com="../pybliographer -q ${srcdir}/../scripts/pybtex.py"

run ${com} ${srcdir}/document ${srcdir}/bibtex.bib > /dev/null
run diff document.bbl ${srcdir}/document.bbl.ref
run rm -f document.bbl

tst_stop

